name: Terraform Apply (Deploy Develop)

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Necessário para autenticação via OIDC na AWS
  contents: read  # Permite checkout do código
  packages: read  # Permite baixar pacotes privados do GitHub Packages

env:
  AWS_REGION: sa-east-1
  ROLE_TO_ASSUME: arn:aws:iam::915153720516:role/GitHubActions-Lambda-Deploy-Role
  WORKING_DIR: ./infra
  LAMBDA_PROJ_PATH: ./app/src/Fiap.FCGames.Notifications.Lambda/Fiap.FCGames.Notifications.Lambda.csproj

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}          

      - name: Build & Package Lambda (.NET 10 ARM64)
        run: |
          dotnet publish ./app/src/Fiap.FCGames.Notifications.Lambda/Fiap.FCGames.Notifications.Lambda.csproj \
            -c Release \
            -r linux-arm64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o ./infra/publish
          
          cd ./infra/publish
          
          # Se o executável não se chamar bootstrap, renomeia/copia
          if [ -f "Fiap.FCGames.Notifications.Lambda" ]; then
            cp Fiap.FCGames.Notifications.Lambda bootstrap
          fi
          
          chmod +x bootstrap
          zip -r ../bootstrap.zip .
        working-directory: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false        